### ISSUE TITLE
module initialization error

### ISSUE THREAD

**Issue by c0bra** [apex/up#228]
up version: 0.1.7

Getting this 500 error in cloudwatch when doing the basic app.js from a windows machine:

```
module initialization error: Error at Object.<anonymous> (/var/task/_proxy.js:15:18)
at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12
 at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
module initialization error: Error
at Object.<anonymous> (/var/task/_proxy.js:15:18)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
```

Having trouble finding any references to an error involving `var/task/_proxy.js:`.

**Comment by tj** [comment]
Ahh yep see #225. I _think_ we have to manually fix permissions while creating the zip, for whatever reason the exec bit(s) seem to be removed when writing to disk on windows
