### ISSUE TITLE
runtime failure on application code restart (No OS threads)

### ISSUE THREAD

**Issue by skabbes** [apex/up#308]
**Details**
Up: version 0.2.2

Application code crashes (?) and then is restarted by up-proxy - which fails.  I cannot tell whether the failure is in up-proxy itself, or if the application code fails on boot.  However, the application never appears to be restarted - which points me to up-proxy.

Just naïvely, it appears as lambda might be limiting the number of OS threads.  I am happy to help debug this, and will provides updates here as I start to unveil this problem. 

`up.json`
```json
{
  "name": "goapi",
  "description": "XXXX",
  "runtime": "golang",
  "regions": ["us-west-2"],
  "environment": {
    "XXX_ENV": "prod"
  },
  "lambda": {
    "memory": 1024,
    "timeout": 300,
    "role": "XXXX"
  },
  "hooks": {
    "build": "./build.sh",
    "clean": "./clean.sh"
  },
  "proxy": {
    "command": "./goapi -api -configDir ./config"
  }
}
```

`up logs`
```
  4:39:01pm INFO response duration: 187 id: 654e08fd-9293-11e7-9000-7f0781224ac6 ip: 66.249.90.110 method: GET path: /query/2178c730ed86445bbb167e8d1760d31a/amby_list.csv query: update=16+d size: 197 kB stage: production status: 200 version: 14
  4:39:15pm INFO response duration: 9 id: 6d8044a8-9293-11e7-bf1a-9b2ed0d0ed35 ip: 35.162.121.38 method: POST path: /notifications/sendPush size: 58 B stage: production status: 200 version: 14
  4:39:15pm ERRO network error: dial tcp 127.0.0.1:41060: getsockopt: connection refused version: 14
  4:39:15pm WARN restarting version: 14
  4:39:15pm INFO found free port 36824 version: 14
  4:39:15pm INFO executing "./goapi -api -configDir ./config" version: 14
  4:39:15pm INFO waiting for http://127.0.0.1:36824 (timeout 5s) version: 14
  4:39:15pm ERRO runtime: failed to create new OS thread (have 2 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
  4:39:15pm ERRO runtime stack:
  4:39:15pm ERRO runtime.throw(0xb022b3, 0x9)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:605 +0x95
runtime.newosproc(0xc42002e000, 0xc42003e000)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/os_linux.go:164 +0x1ad
  4:39:15pm ERRO runtime.newm(0xb2af40, 0x0)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go:1647 +0x158
runtime.main.func1()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go:126 +0x36
  4:39:15pm ERRO runtime.systemstack(0xea6e00)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go:1125
  4:39:15pm ERRO goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:298 fp=0xc42002a780 sp=0xc42002a778 pc=0x459d20
  4:39:15pm ERRO runtime.main()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/proc.go:125 +0x6c fp=0xc42002a7e0 sp=0xc42002a780 pc=0x42cebc
  4:39:15pm ERRO runtime.goexit()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42002a7e8 sp=0xc42002a7e0 pc=0x45c8c1
```

**Comment by skabbes** [comment]
Closing this, It appears to have happened after a restart loop of sorts.  Will debug more and potentially reopen.
