### ISSUE TITLE
Relay plugin don't show errors when app crash 

### ISSUE THREAD

**Issue by hellorachid** [apex/up#359]
## Prerequisites

* [x ] I am running the latest version. (`up upgrade`)
* [ x] I searched to see if the issue already exists.

## Description
When i deployed a nodejs app that crash (i don't know why :D), i check CloudWatch log and i  find that logs don't show any errors, the last thing that log shows before the container shutdown is 

```
{
    "fields": {
        "app": "goalsnote-backend",
        "plugin": "relay",
        "region": "us-west-2",
        "version": "$LATEST"
    },
    "level": "info",
    "timestamp": "2017-10-07T16:27:58.152965352Z",
    "message": "waiting for http://127.0.0.1:37621 to listen (timeout 15s)"
}
```
which doesn't give any info why the app crash.

## Love Up?
💯 
## Solution 

i think Relay plugin must report crash errors as well.

**Comment by yhjor** [comment]
same error here

**Comment by hellorachid** [comment]
@yhjor i resolved the problem by applying two methods : 

- set lambda timeout to 20 or 30s (because of lambda cold start)
- use browsifty to bundle all dependencies with the app.js ( browserify --node ./dist/app.js >  app.js)

i hope this help you

**Comment by yhjor** [comment]
https://github.com/apex/up/issues/359#issuecomment-335009477

Thanks for suggestion

1. It is already 30
2.  I am currently using `backpack build` to bundle the js file, gonna try browserify too

**Comment by hellorachid** [comment]
@yhjor you are welcome, we are here to help each other ;)

**Comment by tj** [comment]
hmmm it should still pass any logs from your app (uncaught exceptions etc) to stderr, but I'll double check

**Comment by pctj101** [comment]
I have a similar issue when using express.  When javascript throws an error, cloudwatch simply "stops logging".  Running the same in `up start` would print something nice like:

```
INFO err { ConfigError: Missing region in config 
    at Request.VALIDATE_REGION (/Users/user/theapp/node_modules/aws-sdk/lib/event_listeners.js:91:45)
    at Request.callListeners (/Users/user/theapp/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/user/theapp/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/user/theapp/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/Users/user/theapp/node_modules/aws-sdk/lib/config.js:320:7)
    at /Users/user/theapp/node_modules/aws-sdk/lib/config.js:338:9
    at SharedIniFileCredentials.get (/Users/user/theapp/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/Users/user/theapp/node_modules/aws-sdk/lib/config.js:332:24)
    at Config.getCredentials (/Users/user/theapp/node_modules/aws-sdk/lib/config.js:352:9)
    at Request.VALIDATE_CREDENTIALS (/Users/user/theapp/node_modules/aws-sdk/lib/event_listeners.js:80:26)
  message: 'Missing region in config',
  code: 'ConfigError',
  time: 2017-11-25T19:36:44.478Z }

```

**Comment by tj** [comment]
Flushing isn't completely synchronized yet, I'll try and fix that soon but 971c4f3178f01e0e0c1cc91e49e0c42f79ac19ce should improve that scenario
