### ISSUE TITLE
`up env` error after `up env add ...`

### ISSUE THREAD

**Issue by holic** [apex/up#433]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.

## Description

`up env` is perpetually erroring out after running `up env add ...`

## Steps to Reproduce

```
$ up --version

0.1.9-pro

$ up env add MAILGUN_API_KEY [reacted]

     Added MAILGUN_API_KEY

$ up env --verbose

     5ms     DEBU up version 0.1.9-pro
     0s      DEBU infer name from current working directory "inquiries"
     0s      DEBU region from aws shared config "us-west-1"
   ⠹ 298ms   DEBU track "List Secrets" map[version:0.1.9-pro plan:pro os:darwin arch:amd64]panic: runtime error: index out of range

goroutine 1 [running]:
github.com/apex/up/platform/lambda/runtime.(*Secrets).List(0xc42029cff0, 0x0, 0x0, 0x22232e0, 0xc42029cff0, 0x4)
	/Users/tj/dev/src/github.com/apex/up/platform/lambda/runtime/secrets.go:65 +0x9e4
github.com/apex/up/internal/cli/env.list.func1(0xc42028abd0, 0x1010a33, 0x1a009c0)
	/Users/tj/dev/src/github.com/apex/up/internal/cli/env/env.go:48 +0xc3
github.com/apex/up/vendor/github.com/tj/kingpin.(*actionMixin).applyActions(0xc420225788, 0xc42028abd0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/up/vendor/github.com/tj/kingpin/actions.go:33 +0x6d
github.com/apex/up/vendor/github.com/tj/kingpin.(*Application).applyActions(0xc420093d40, 0xc42028abd0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/up/vendor/github.com/tj/kingpin/app.go:570 +0xe1
github.com/apex/up/vendor/github.com/tj/kingpin.(*Application).execute(0xc420093d40, 0xc42028abd0, 0xc42023e720, 0x2, 0x2, 0x0, 0x0, 0x1, 0xc420244098)
	/Users/tj/dev/src/github.com/apex/up/vendor/github.com/tj/kingpin/app.go:406 +0x8f
github.com/apex/up/vendor/github.com/tj/kingpin.(*Application).Parse(0xc420093d40, 0xc4200100d0, 0x2, 0x2, 0x274a48a78000, 0x1, 0xc42026a5a0, 0xc420240850)
	/Users/tj/dev/src/github.com/apex/up/vendor/github.com/tj/kingpin/app.go:222 +0x1f2
github.com/apex/up/internal/cli/app.Run(0x1c176f0, 0x9, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/up/internal/cli/app/app.go:16 +0xed
main.run(0x1b5fe2d, 0xa)
	/Users/tj/dev/src/github.com/apex/up/cmd/up/main.go:69 +0x206
main.main()
	/Users/tj/dev/src/github.com/apex/up/cmd/up/main.go:45 +0x8a
```

## Love Up?

Please consider donating https://opencollective.com/apex-up/donate to help the project.

Just have a general question? Join us on Slack https://apex-slackin.herokuapp.com/

**Comment by holic** [comment]
Also, no rush on this on Thanksgiving! Just playing around with `up` while the family watches the Macy's Thanksgiving Day Parade.

**Comment by holic** [comment]
Looks like removing this environment variable (since I know the key) with `up env rm MAILGUN_API_KEY` fixes `up env`. Seems that the error only appears when there are environment variables stored.

**Comment by tj** [comment]
hmm strange, looks like it's not responding with a user ARN so I can't grab the name, it should show the last modified user.

```
   λ site (master): up env add MAILGUN_API_KEY foo

     Added MAILGUN_API_KEY

   λ site (master): up env
                                                              
     all                                                      
                                                           
     MAILGUN_API_KEY  -  -  Modified 2 seconds ago by tobi 
```

I'll have a fix for that right away! And yep, the `AWS_*` stuff is actually from Lambda itself, the role assigned to the function.

**Comment by tj** [comment]
`up upgrade` to grab v0.1.10, should be good to go!

**Comment by tj** [comment]
closing but please re-open if there's an issue! thanks for the report
