### ISSUE TITLE
Flask application fails to run and fails to build

### ISSUE THREAD

**Issue by wpapper** [apex/up#589]
## Prerequisites

* [X] I am running the latest version. (`up upgrade`)
* [X] I searched to see if the issue already exists.
* [X] I inspected the verbose debug output with the `-v, --verbose` flag.
* [X] Are you an Up Pro subscriber?

## Description

I am trying to set up a very simple, three-line Flask app with Up. The application builds successfully and is loaded onto AWS Lambda. However, calling the application's endpoint fails with `ERRO ImportError: No module named pkg_resources`. This error message appears with or without pipenv. I tried following the instructions at [this link](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources), but they didn't work.

I decided to try the Flask project in `up-examples`, but this does not build successfully. Instead, it fails with the message:
```
(python-flask-D9xZkjkt) bash-3.2$ up --verbose
     5ms     DEBU up version 0.5.2-pro
   ⠋ 0s      DEBU region from aws shared config "us-east-1"
     768ms   DEBU region from aws shared config "us-east-1"
     0s      DEBU event deploy map[]
     0s      DEBU event platform.build map[]
     0s      DEBU hook prebuild is not defined
     0s      DEBU event hook map[name:build hook:[mkdir -p .pypath/ && pip install -r requirements.txt -t .pypath/]]
     1.341s  DEBU hook "build" command "mkdir -p .pypath/ && pip install -r requirements.txt -t .pypath/"
   ⠙ 0s      DEBU event hook.complete map[name:build hook:[mkdir -p .pypath/ && pip install -r requirements.txt -t .py     0s      DEBU event hook.complete map[name:build hook:[mkdir -p .pypath/ && pip install -r requirements.txt -t .pypath/] duration:1.341393463s]
   ⠙ 0s      DEBU event platform.build.complete map[duration:1.341701532s]
     0s      DEBU event platform.build.complete map[duration:1.341701532s]
   ⠙ 0s      DEBU event deploy.complete map[duration:1.341859677s]
     Error: building: "build" hook: "mkdir -p .pypath/ && pip install -r requirements.txt -t .pypath/": Collecting Flask==0.12.2 (from -r requirements.txt (line 1))
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting Jinja2==2.9.6 (from -r requirements.txt (line 2))
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 3))
Collecting Werkzeug==0.12.2 (from -r requirements.txt (line 4))
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting click==6.7 (from -r requirements.txt (line 5))
  Using cached click-6.7-py2.py3-none-any.whl
Collecting itsdangerous==0.24 (from -r requirements.txt (line 6))
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 7))
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jg/cf1qrj_n1b98tyb416ps19pm0000gn/T/pip-build-hacgl1y8/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/jg/cf1qrj_n1b98tyb416ps19pm0000gn/T/pip-build-hacgl1y8/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Setuptools version",version,"or greater has been installed.")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jg/cf1qrj_n1b98tyb416ps19pm0000gn/T/pip-build-hacgl1y8/wsgiref/
```

I am running Python 3.6.4, which I installed via Homebrew on OS X. Some additional info about my system:
To get sh to run successfully when originally testing `up`, I had to add the following to my `.profile`:
```
# To get sh to run .profile
env ENV=$HOME/.profile /bin/sh
```

This is due to the fact that I aliased python3 to python, and the same for pip, in my `.profile`:
```
alias python=python3
alias pip=pip3
```

Removing these aliases didn't seem to fix the issue. When the aliases are removed, the error messages are identical.

## Steps to Reproduce

1. Navigate to `python-flask` in `up-examples`
2. Run `up`

**Comment by tj** [comment]
I don't know much about Python but if it's expecting python3 you could try adding `proxy.command` to change the version in Lambda:

```json
{
  "stages": {
    "staging": {
      "proxy": {
        "command": "python3 app.py"
      }
    }
  }
}
```

**Comment by tj** [comment]
Can't seem to reproduce this error :'( — if any python pros come through this issue, definitely let me know if there's a better way to inline deps than the following inferred `build` hook:

```
mkdir -p .pypath/ && pip install -r requirements.txt -t .pypath/
```

**Comment by tj** [comment]
I think this is more of a personal setup issue. I'll close for now but definitely let me know if there's something more idiomatic.

```
$ mkdir -p .pypath/ && pip install -r requirements.txt -t .pypath/
Collecting Flask==0.12.2 (from -r requirements.txt (line 1))
  Using cached Flask-0.12.2-py2.py3-none-any.whl
Collecting Jinja2==2.9.6 (from -r requirements.txt (line 2))
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting MarkupSafe==1.0 (from -r requirements.txt (line 3))
Collecting Werkzeug==0.12.2 (from -r requirements.txt (line 4))
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting click==6.7 (from -r requirements.txt (line 5))
  Using cached click-6.7-py2.py3-none-any.whl
Collecting itsdangerous==0.24 (from -r requirements.txt (line 6))
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 7))
Installing collected packages: itsdangerous, click, Werkzeug, MarkupSafe, Jinja2, Flask, wsgiref
Successfully installed Flask-0.12.2 Jinja2-2.9.6 MarkupSafe-1.0 Werkzeug-0.12.2 click-6.7 itsdangerous-0.24 wsgiref-0.1.2
```
