### ISSUE TITLE
up logs 'not info' fails

### ISSUE THREAD

**Issue by kaihendry** [apex/up#724]
Using 0.7.8-pro

```
[hendry@t480s invite]$ up logs 'not info'
panic: log "/aws/lambda/processinvitations": InvalidParameterException: Invalid character(s) in term '!('
        status code: 400, request id: 22efb02f-dc09-11e8-875f-3552217aa683

goroutine 11 [running]:
github.com/apex/up/platform/aws/logs.(*Logs).start(0xc000120d00)
        /Users/tj/dev/src/github.com/apex/up/platform/aws/logs/logs.go:108 +0x72b
created by github.com/apex/up/platform/aws/logs.New
        /Users/tj/dev/src/github.com/apex/up/platform/aws/logs/logs.go:52 +0x30c
```

https://youtu.be/66YOCrG_WJQ?t=356

**Comment by tj** [comment]
hmm I might have to remove those examples, I thought ! was supported but now I'm not sure it is.
