### ISSUE TITLE
Failed deployment sapper application

### ISSUE THREAD

**Issue by xncbf** [apex/up#800]
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [ ] Are you an Up Pro subscriber?

## Description

I deployed by `up`. but i can not enter site.
```
{
"message": "Internal server error"
}
```

`up stack`
```
?[38;5;61mstatus:?[0;00m Created
```

`up build`
```
   ?[38;5;61m⠋ build:?[0;00m
?[?25h
     ?[38;5;125mError:?[0;00m building: "build" hook: "npm run build":
```

## logs
`up logs -f -v`

```

     1ms     ?[38;5;102mDEBU?[0;00m ?[38;5;102mpoll?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488661174
     2.052s  ?[38;5;102mDEBU?[0;00m ?[38;5;102mrequest?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488661174
     2ms     ?[38;5;102mDEBU?[0;00m ?[38;5;102mpoll?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488661175
     2.031s  ?[38;5;102mDEBU?[0;00m ?[38;5;102mrequest?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488661175
     1ms     ?[38;5;102mDEBU?[0;00m ?[38;5;102mpoll?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488661176
   ⠇ 5ms     ?[38;5;102mDEBU?[0;00m ?[38;5;102mrequest?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488661176  ?[38;5;102mFeb 1st 01:37:41am?[0;00m ?[1m?[38;5;61mINFO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61mstarted app?[0;00m
  ?[38;5;102mFeb 1st 01:37:41am?[0;00m ?[1m?[38;5;61mINFO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61mwaiting for app to listen on PORT?[0;00m
  ?[38;5;102mFeb 1st 01:37:41am?[0;00m ?[1m?[38;5;61mINFO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61mStarting server on port 37017?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m/var/task/node_modules/session-file-store/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:45?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m        throw err0?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m        ^?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61mError: EROFS: read-only file system, mkdir '/var/task/.sessions'?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Object.mkdirSync (fs.js:757:3)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Object.mkdirsSync (/var/task/node_modules/session-file-store/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at new FileStore (/var/task/node_modules/session-file-store/lib/session-file-store.js:29:8)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Object.<anonymous> (/var/task/__sapper__/build/server/server.js:3895:10)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Module._compile (internal/modules/cjs/loader.js:778:30)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Module.load (internal/modules/cjs/loader.js:653:32)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Function.Module._load (internal/modules/cjs/loader.js:585:3)?[0;00m
  ?[38;5;102mFeb 1st 01:37:42am?[0;00m ?[1m?[38;5;125mERRO?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61m    at Module.require (internal/modules/cjs/loader.js:692:17)?[0;00m
  ?[38;5;102mFeb 1st 01:37:56am?[0;00m ?[1m?[38;5;125mFATA?[0;00m?[0m ?[38;5;102mstaging?[0;00m ?[38;5;102m0a0381d?[0;00m ?[38;5;61merror creating handler: waiting for http://127.0.0.1:37017 to be in listening state: timed out after 15s?[0;00m?[38;5;102m:?[0;00m ?[38;5;125mname?[0;00m?[38;5;102m=?[0;00mrazberry-svelte ?[38;5;125mtype?[0;00m?[38;5;102m=?[0;00mserver
  ?[38;5;102mFeb 1st 01:37:56am?[0;00m ?[1m?[38;5;61mINFO?[0;00m?[0m ?[38;5;61m2020-01-31T16:37:56.190Z 5cbf30cb-9dc0-4476-85a6-1b2f67a52640    ERROR   [shim] exit: code=1 signal=null?[0;00m
  ?[38;5;102mFeb 1st 01:37:56am?[0;00m ?[1m?[38;5;61mINFO?[0;00m?[0m ?[38;5;61mREPORT RequestId: 5cbf30cb-9dc0-4476-85a6-1b2f67a52640   Duration: 15290.88 ms   Billed Duration: 15300 ms       Memory
Size: 512 MB    Max Memory Used: 52 MB  ?[0;00m
  ?[38;5;102mFeb 1st 01:37:56am?[0;00m ?[1m?[38;5;61mINFO?[0;00m?[0m ?[38;5;61mRequestId: 5cbf30cb-9dc0-4476-85a6-1b2f67a52640 Error: Runtime exited with error: exit status 1
Runtime.ExitError?[0;00m
     2.074s  ?[38;5;102mDEBU?[0;00m ?[38;5;102mrequest?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488661176
     1ms     ?[38;5;102mDEBU?[0;00m ?[38;5;102mpoll?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488676245
     2.053s  ?[38;5;102mDEBU?[0;00m ?[38;5;102mrequest?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488676245
     1ms     ?[38;5;102mDEBU?[0;00m ?[38;5;102mpoll?[0;00m ?[38;5;102mgroup?[0;00m?[38;5;102m=?[0;00m/aws/lambda/razberry-svelte ?[38;5;102mstart?[0;00m?[38;5;102m=?[0;00m1580488676246
```

## cloudwatch logs
```
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.132957061Z",
    "message": "/var/task/node_modules/session-file-store/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:45"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.13308418Z",
    "message": "        throw err0"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133117445Z",
    "message": "        ^"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133146923Z",
    "message": ""
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133155069Z",
    "message": "Error: EROFS: read-only file system, mkdir '/var/task/.sessions'"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133163064Z",
    "message": "    at Object.mkdirSync (fs.js:757:3)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133185887Z",
    "message": "    at Object.mkdirsSync (/var/task/node_modules/session-file-store/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133201054Z",
    "message": "    at new FileStore (/var/task/node_modules/session-file-store/lib/session-file-store.js:29:8)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133233658Z",
    "message": "    at Object.<anonymous> (/var/task/__sapper__/build/server/server.js:3895:10)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133256216Z",
    "message": "    at Module._compile (internal/modules/cjs/loader.js:778:30)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133288995Z",
    "message": "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133322372Z",
    "message": "    at Module.load (internal/modules/cjs/loader.js:653:32)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133346106Z",
    "message": "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.1335222Z",
    "message": "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "plugin": "relay",
        "region": "ap-northeast-2",
        "stage": "staging",
        "version": "3"
    },
    "level": "error",
    "timestamp": "2020-01-31T17:19:54.133553398Z",
    "message": "    at Module.require (internal/modules/cjs/loader.js:692:17)"
}
{
    "fields": {
        "app": "razberry-svelte",
        "commit": "106ea6c",
        "name": "razberry-svelte",
        "region": "ap-northeast-2",
        "stage": "staging",
        "type": "server",
        "version": "3"
    },
    "level": "fatal",
    "timestamp": "2020-01-31T17:20:07.973996892Z",
    "message": "error creating handler: waiting for http://127.0.0.1:41759 to be in listening state: timed out after 15s"
}
```

## Steps to Reproduce

```
git clone https://github.com/bberry-com/razberry-frontend
git add .
git commit -m "somthing"
git push // (I'm using github actions 'apex/actions/up@master')
```

**Comment by michaelcuneo** [comment]
@xncbf I'm getting the same problem, do you know how you solved this?
