### ISSUE TITLE
up stack status panic

### ISSUE THREAD

**Issue by jpillora** [apex/up#809]
Let me know if you need more 👍

```
$ up version
1.5.1

$ up stack status

     status: Created

     Production

     domain: mycooldomainforthisissue.jpillora.com

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x18f2db0]

goroutine 1 [running]:
github.com/apex/up/platform/lambda/stack.(*Stack).showCloudfront(0xc0002ac0a0, 0xc0000da9a0, 0x19, 0xc0005590b0)
	/Users/tj/dev/src/github.com/apex/up/platform/lambda/stack/stack.go:433 +0x120
github.com/apex/up/platform/lambda/stack.(*Stack).Show(0xc0002ac0a0, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/up/platform/lambda/stack/stack.go:166 +0x32a
github.com/apex/up/platform/lambda.(*Platform).ShowStack(0xc00029c6c0, 0x1d61649, 0xe, 0xc00029c870, 0xc00008c100)
	/Users/tj/dev/src/github.com/apex/up/platform/lambda/lambda.go:276 +0x6a
github.com/apex/up.(*Project).ShowStack(0xc00024db20, 0x1d61649, 0xe, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/up/up.go:194 +0x141
github.com/apex/up/internal/cli/stack.status.func1(0xc0001dd830, 0x100c1b3, 0x1bd53a0)
	/Users/tj/dev/src/github.com/apex/up/internal/cli/stack/stack.go:140 +0xac
github.com/tj/kingpin.(*actionMixin).applyActions(0xc0002373c8, 0xc0001dd830, 0x0, 0x0)
	/Users/tj/dev/pkg/mod/github.com/tj/kingpin@v2.5.0+incompatible/actions.go:33 +0x6d
github.com/tj/kingpin.(*Application).applyActions(0xc00022ca20, 0xc0001dd830, 0x0, 0x0)
	/Users/tj/dev/pkg/mod/github.com/tj/kingpin@v2.5.0+incompatible/app.go:570 +0xdc
github.com/tj/kingpin.(*Application).execute(0xc00022ca20, 0xc0001dd830, 0xc00024cf80, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc0000105c8)
	/Users/tj/dev/pkg/mod/github.com/tj/kingpin@v2.5.0+incompatible/app.go:406 +0x8f
github.com/tj/kingpin.(*Application).Parse(0xc00022ca20, 0xc000020070, 0x2, 0x2, 0x0, 0x8, 0xc000219df0, 0x1014cc2)
	/Users/tj/dev/pkg/mod/github.com/tj/kingpin@v2.5.0+incompatible/app.go:222 +0x1fe
github.com/apex/up/internal/cli/app.Run(0x1ef9aac, 0x5, 0x0, 0x0)
	/Users/tj/dev/src/github.com/apex/up/internal/cli/app/app.go:16 +0x107
main.run(0x1d5d406, 0xa)
	/Users/tj/dev/src/github.com/apex/up/cmd/up/main.go:68 +0x21d
main.main()
	/Users/tj/dev/src/github.com/apex/up/cmd/up/main.go:43 +0xcd
```

**Comment by tj** [comment]
thanks for the report! I'll see if I can figure out what's going on there

**Comment by tj** [comment]
This is for the OSS version right? The line numbers are a bit different in Pro/OSS. I think I see where it would be panicing, but it's a bit strange that AWS is not responding with any data there

**Comment by jpillora** [comment]
Yep OSS

**Comment by tj** [comment]
k cool thanks! I'll have a fix in there soon
